name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/test_data_loader.py
          pytest tests/test_data_validator.py
          pytest tests/test_report_generator.py

      - name: Generate Report
        run: |
          mkdir -p reports
          python src/data_processing_workflow.py

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: generated-reports
          path: reports